### ISSUE TITLE
Some questions about loading data during training

### ISSUE THREAD

**Issue by wy3406** [duducheng/deeplabv3p_gluon#2]
Hi,
   The problem occurred when I ran the trian.py file.When I run to the 165 line in train.py(_, best_mIoU = trainer.validation("INIT")) ,then turn to validation(self, epoch, train=False) function. Running here to{ for I, (x, y) in enumerate (tbar):}can not be carried out. then I went to the { mylib/voc_aug.py } file to find the {VOCAugSegmentation.__getitem__} function.this {VOCAugSegmentation.__getitem__} function was called 16 times and stuck.The program didn't respond after 16 calls to this function. I waited for half an hour and still didn't respond. Why? I know that the problem is the loading of data, but we can not know the specific reasons.

---------------------------------------------------------------------
My param config:
BATCH=4
TEST_BATCH=16
TRAIN_SPLIT='trainval'
TRAIN_OS=16
USE_GLOBAL_STATS=True

My running environment：
mxnet version==1.2.1
gluoncv==0.3.0
python==3.6
operating system==ubuntu 16.04
cuda==9.0
gpu==1080Ti

**Comment by duducheng** [comment]
Thanks for reporting your problems. I wish to help but I have not encountered this problem before, since the code works well on both AWS (V100 / P100) and my local machines (1080 / Titan Xp). 

According to your description, I doubt that the problem coming from your own data / system. I suggest that you may check whether your image files were damage, especially, the 16th file if it always happens at the 16th calls. Or you should also check your memory dynamically. All my test environments have at least 32 GB memories. 

Good luck!

**Comment by wy3406** [comment]
Thank you for your reply.The reason I found the problem was that the parameter {num_workers} of the {gluon. data. Dataloader} function defaults to 4 and works properly when set to 0.
